# Generated by Django 5.2.7 on 2025-10-09 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='updated_at',
            new_name='last_activity',
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AddField(
            model_name='progress',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='total_lessons',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
