# Generated by Django 5.2.7 on 2025-10-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_updated_at_progress_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
