# Generated by Django 5.2.7 on 2025-10-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assignment_studentassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('student', 'course')},
        ),
        migrations.AlterField(
            model_name='progress',
            name='completed_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='total_lessons',
            field=models.IntegerField(default=10),
        ),
        migrations.RemoveField(
            model_name='progress',
            name='notes',
        ),
    ]
