# Generated by Django 5.2.7 on 2025-10-13 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_progress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course', 'order']},
        ),
        migrations.RemoveField(
            model_name='studentlessonprogress',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, help_text='HTML content for the lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentlessonprogress',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='30 minutes', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
