# Generated by Django 5.2.7 on 2025-10-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentlessonprogress',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
